language: python
sudo: false
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
env:
  matrix:
    # This environment tests the newest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="3.8" INSTALL_MKL="true"
      NUMPY_VERSION="1.9.2" SCIPY_VERSION="0.15.1"
install:
  - source ci/install.sh
script: nosetests --with-coverage --cover-package=chowmein
after_success:
  coveralls